<?php

namespace Tienvx\Bundle\MbtBundle\Tests\Message;

use Doctrine\ORM\EntityManagerInterface;
use Tienvx\Bundle\MbtBundle\Entity\Bug;
use Tienvx\Bundle\MbtBundle\Entity\Generator;
use Tienvx\Bundle\MbtBundle\Entity\Model;
use Tienvx\Bundle\MbtBundle\Entity\Reducer;
use Tienvx\Bundle\MbtBundle\Entity\Reporter;
use Tienvx\Bundle\MbtBundle\Entity\Task;
use Tienvx\Bundle\MbtBundle\Graph\Path;

class BugMessageTest extends MessageTestCase
{
    /**
     * @param string $model
     * @param array  $steps
     * @param string $reducer
     * @param array  $expectedSteps
     * @dataProvider consumeMessageData
     *
     * @throws \Exception
     */
    public function testExecute(string $model, array $steps, string $reducer, array $expectedSteps)
    {
        /** @var EntityManagerInterface $entityManager */
        $entityManager = self::$container->get(EntityManagerInterface::class);
        $path = new Path($steps);
        $expectedPath = new Path($expectedSteps);
        switch ($model) {
            case 'shopping_cart':
                $bugMessage = 'You added an out-of-stock product into cart! Can not checkout';
                break;
            case 'checkout':
                $bugMessage = 'Still able to do register account, guest checkout or login when logged in!';
                break;
            case 'product':
                $bugMessage = 'Can not upload file!';
                break;
            default:
                // Make PHP happy
                $bugMessage = '';
                break;
        }

        $task = new Task();
        $task->setTitle('Test task title');
        $task->setModel(new Model($model));
        $task->setGenerator(new Generator('random'));
        $task->setReducer(new Reducer($reducer));
        $task->setTakeScreenshots(false);
        $task->setReporters([new Reporter('in-memory')]);
        // Does not matter, because we are testing reducer.
        //$task->setGeneratorOptions($generatorOptions);
        $entityManager->persist($task);

        $entityManager->flush();

        $this->clearMessages();
        $this->clearReport();
        // Just to make sure
        $this->removeScreenshots();

        $bug = new Bug();
        $bug->setTitle('Test bug title');
        $bug->setPath($path);
        $bug->setLength($path->countPlaces());
        $bug->setTask($task);
        $bug->setBugMessage($bugMessage);
        $entityManager->persist($bug);

        $entityManager->flush();

        $this->consumeMessages();

        $entityManager->refresh($bug);

        /** @var Bug[] $bugs */
        $bugs = $entityManager->getRepository(Bug::class)->findBy(['task' => $task->getId()]);

        $this->assertEquals(1, count($bugs));
        $this->assertEquals($bugMessage, $bugs[0]->getBugMessage());
        if ('random' !== $reducer) {
            $this->assertEquals(Path::serialize($expectedPath), Path::serialize($bugs[0]->getPath()));
            $this->assertEquals($expectedPath->countPlaces(), $bugs[0]->getLength());
        } else {
            $this->assertLessThanOrEqual($expectedPath->countPlaces(), $bugs[0]->getLength());
        }

        $this->assertTrue($this->hasReport($bugs[0]));
        $this->assertEquals('reported', $bug->getStatus());

        // Because screenshots had not been captured, and had been removed during set-up, no need to test this
        //$this->assertTrue($this->reportHasScreenshot());
    }

    public function consumeMessageData()
    {
        return [
            [
                'shopping_cart',
                [
                    [null, null, ['home']],
                    ['viewAnyCategoryFromHome', ['category' => 57], ['category']],
                    ['addFromCategory', ['product' => 49], ['category']],
                    ['checkoutFromCategory', [], ['checkout']],
                ],
                'split',
                [
                    [null, null, ['home']],
                    ['viewAnyCategoryFromHome', ['category' => 57], ['category']],
                    ['addFromCategory', ['product' => 49], ['category']],
                    ['checkoutFromCategory', [], ['checkout']],
                ],
            ],
            [
                'shopping_cart',
                [
                    [null, null, ['home']],
                    ['viewAnyCategoryFromHome', ['category' => '34'], ['category']],
                    ['viewProductFromCategory', ['product' => '48'], ['product']],
                    ['addFromProduct', [], ['product']],
                    ['checkoutFromProduct', [], ['checkout']],
                    ['viewCartFromCheckout', [], ['cart']],
                    ['viewProductFromCart', ['product' => '48'], ['product']],
                    ['viewAnyCategoryFromProduct', ['category' => '57'], ['category']],
                    ['addFromCategory', ['product' => '49'], ['category']],
                    ['checkoutFromCategory', [], ['checkout']],
                ],
                'loop',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '34',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '48',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '40',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'split',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '33',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '31',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewCartFromCategory',
                        [
                        ],
                        [
                            'cart',
                        ],
                    ],
                    [
                        'backToHomeFromCart',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'addFromProduct',
                        [
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'checkoutFromProduct',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'loop',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'addFromProduct',
                        [
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'checkoutFromProduct',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '34',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '48',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'backToHomeFromProduct',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'checkoutFromHome',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'split',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewCartFromHome',
                        [
                        ],
                        [
                            'cart',
                        ],
                    ],
                    [
                        'backToHomeFromCart',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '25_28',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '20',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'loop',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'checkoutFromHome',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                    [
                        'backToHomeFromCheckout',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '20',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '46',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '33',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewCartFromCategory',
                        [
                        ],
                        [
                            'cart',
                        ],
                    ],
                    [
                        'viewProductFromCart',
                        [
                            'product' => '46',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'loop',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '20',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '33',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '20_27',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '41',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '24',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '17',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '24',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '28',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'addFromProduct',
                        [
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '20',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '33',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'loop',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '20_27',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '41',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromProduct',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewOtherCategory',
                        [
                            'category' => '34',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewProductFromCategory',
                        [
                            'product' => '48',
                        ],
                        [
                            'product',
                        ],
                    ],
                    [
                        'backToHomeFromProduct',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'checkoutFromHome',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'split',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'viewCartFromCategory',
                        [
                        ],
                        [
                            'cart',
                        ],
                    ],
                    [
                        'backToHomeFromCart',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'checkoutFromHome',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'split',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'checkout',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'addProductAndCheckoutNotLoggedIn',
                        [
                        ],
                        [
                            'awaitingAccount',
                        ],
                    ],
                    [
                        'guestCheckout',
                        [
                        ],
                        [
                            'awaitingPersonalDetails',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillPersonalDetails',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillBillingAddress',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'billingAddressFilled',
                        ],
                    ],
                    [
                        'guestCheckoutAndAddBillingAddress',
                        [
                        ],
                        [
                            'accountAdded',
                            'billingAddressAdded',
                            'awaitingDeliveryAddress',
                        ],
                    ],
                    [
                        'useExistingDeliveryAddress',
                        [
                        ],
                        [
                            'accountAdded',
                            'billingAddressAdded',
                            'deliveryAddressAdded',
                            'awaitingDeliveryMethod',
                        ],
                    ],
                    [
                        'addDeliveryMethod',
                        [
                        ],
                        [
                            'accountAdded',
                            'billingAddressAdded',
                            'deliveryAddressAdded',
                            'deliveryMethodAdded',
                            'awaitingPaymentMethod',
                        ],
                    ],
                    [
                        'addPaymentMethod',
                        [
                        ],
                        [
                            'accountAdded',
                            'billingAddressAdded',
                            'deliveryAddressAdded',
                            'deliveryMethodAdded',
                            'paymentMethodAdded',
                            'awaitingOrderConfirm',
                        ],
                    ],
                    [
                        'confirmOrder',
                        [
                        ],
                        [
                            'orderPlaced',
                        ],
                    ],
                    [
                        'continueShopping',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addProductAndCheckoutNotLoggedIn',
                        [
                        ],
                        [
                            'awaitingAccount',
                        ],
                    ],
                    [
                        'registerAccount',
                        [
                        ],
                        [
                            'awaitingPersonalDetails',
                            'awaitingPassword',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillPersonalDetails',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'awaitingPassword',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillPassword',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'passwordFilled',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillBillingAddress',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'passwordFilled',
                            'billingAddressFilled',
                        ],
                    ],
                    [
                        'registerAndAddBillingAddress',
                        [
                        ],
                        [
                            'accountAdded',
                            'billingAddressAdded',
                            'awaitingDeliveryAddress',
                        ],
                    ],
                ],
                'loop',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'addProductAndCheckoutNotLoggedIn',
                        [
                        ],
                        [
                            'awaitingAccount',
                        ],
                    ],
                    [
                        'registerAccount',
                        [
                        ],
                        [
                            'awaitingPersonalDetails',
                            'awaitingPassword',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillPersonalDetails',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'awaitingPassword',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillPassword',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'passwordFilled',
                            'awaitingBillingAddress',
                        ],
                    ],
                    [
                        'fillBillingAddress',
                        [
                        ],
                        [
                            'personalDetailsFilled',
                            'passwordFilled',
                            'billingAddressFilled',
                        ],
                    ],
                    [
                        'registerAndAddBillingAddress',
                        [
                        ],
                        [
                            'accountAdded',
                            'billingAddressAdded',
                            'awaitingDeliveryAddress',
                        ],
                    ],
                ],
            ],
            [
                'shopping_cart',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '40',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'checkoutFromHome',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                    [
                        'backToHomeFromCheckout',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '42',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '30',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '43',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
                'random',
                [
                    [
                        null,
                        null,
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '40',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'checkoutFromHome',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                    [
                        'backToHomeFromCheckout',
                        [
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '42',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '30',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'addFromHome',
                        [
                            'product' => '43',
                        ],
                        [
                            'home',
                        ],
                    ],
                    [
                        'viewAnyCategoryFromHome',
                        [
                            'category' => '57',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'addFromCategory',
                        [
                            'product' => '49',
                        ],
                        [
                            'category',
                        ],
                    ],
                    [
                        'checkoutFromCategory',
                        [
                        ],
                        [
                            'checkout',
                        ],
                    ],
                ],
            ],
            [
                'product',
                [
                    [
                        null,
                        null,
                        [
                            'product',
                        ],
                    ],
                    [
                        'selectOptions',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingText',
                            'awaitingSelect',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'awaitingTime',
                            'awaitingDateTime',
                        ],
                    ],
                    [
                        'selectSelect',
                        [
                            'select' => 2,
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingText',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'awaitingTime',
                            'awaitingDateTime',
                            'selectSelected',
                        ],
                    ],
                    [
                        'selectTime',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingText',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'awaitingDateTime',
                            'selectSelected',
                            'timeSelected',
                        ],
                    ],
                    [
                        'selectDateTime',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingText',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'selectSelected',
                            'timeSelected',
                            'dateTimeSelected',
                        ],
                    ],
                    [
                        'fillText',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'selectSelected',
                            'timeSelected',
                            'dateTimeSelected',
                            'textFilled',
                        ],
                    ],
                    [
                        'selectFile',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'selectSelected',
                            'timeSelected',
                            'dateTimeSelected',
                            'textFilled',
                        ],
                    ],
                ],
                'transition',
                [
                    [
                        null,
                        null,
                        [
                            'product',
                        ],
                    ],
                    [
                        'selectOptions',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingText',
                            'awaitingSelect',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'awaitingTime',
                            'awaitingDateTime',
                        ],
                    ],
                    [
                        'selectFile',
                        [
                        ],
                        [
                            'awaitingRadio',
                            'awaitingCheckbox',
                            'awaitingTextarea',
                            'awaitingFile',
                            'awaitingDate',
                            'awaitingSelect',
                            'awaitingTime',
                            'awaitingDateTime',
                            'awaitingText',
                        ],
                    ],
                ],
            ],
        ];
    }
}
